version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - cdk bootstrap
      - cdk synth
      - cdk deploy --verbose --require-approval never
artifacts:
  files:
    - '**/*'
